# Direct configuration for RP2040
MCU = RP2040
BOOTLOADER = rp2040
SERIAL_DRIVER = vendor

# Build Options
SPLIT_KEYBOARD = yes
BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = yes
RGB_MATRIX_ENABLE = yes
ENCODER_ENABLE = yes
